add fi

diff --git a/.github/workflows/reusable-get-version-name.yml b/.github/workflows/reusable-get-version-name.yml
--- a/.github/workflows/reusable-get-version-name.yml
+++ b/.github/workflows/reusable-get-version-name.yml
@@ -21,18 +21,17 @@ jobs:
                 if: ${{ inputs.version-source == 'internal' }}
                 uses: actions/checkout@v4
 
-            - name: Extract version
-              id: extract
-              run: |
-                  if [ "${{ inputs.version-source }}" = "branch" ]; then
-                    last_part="${GITHUB_REF_NAME##*/}"
-                    echo "version-name=$last_part" >> "$GITHUB_OUTPUT"
-                  
-                  elif [ "${{ inputs.version-source }}" = "internal" ]; then
-                    version_name=$(grep 'set("VERSION_NAME",' build-logic/build_properties.gradle.kts \
-                      | sed -E 's/.*set\("VERSION_NAME",[[:space:]]*"([^"]+)".*/\1/')
-                    echo "version-name=$version_name" >> "$GITHUB_OUTPUT"
-                  
-                  else
-                    echo "Error: Unknown version-source '${{ inputs.version-source }}'"
-                    exit 1
+            -   name: Extract version
+                id: extract
+                run: |
+                    if [ "${{ inputs.version-source }}" = "branch" ]; then
+                      last_part="${GITHUB_REF_NAME##*/}"
+                      echo "version-name=$last_part" >> "$GITHUB_OUTPUT"                
+                    elif [ "${{ inputs.version-source }}" = "internal" ]; then
+                      version_name=$(grep 'set("VERSION_NAME",' build-logic/build_properties.gradle.kts \
+                        | sed -E 's/.*set\("VERSION_NAME",[[:space:]]*"([^"]+)".*/\1/')
+                      echo "version-name=$version_name" >> "$GITHUB_OUTPUT"
+                    else
+                      echo "Error: Unknown version-source '${{ inputs.version-source }}'"
+                      exit 1
+                    fi
